/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(CC2F2ByteVector.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e1b9616c3e4c6b4a11825a9f73c3c9ac)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lfast/CC2F2ByteVector.h>
// pydoc.h is automatically generated in the build directory
#include <CC2F2ByteVector_pydoc.h>

void bind_CC2F2ByteVector(py::module& m)
{

    using CC2F2ByteVector    = ::gr::lfast::CC2F2ByteVector;


    py::class_<CC2F2ByteVector, gr::sync_decimator,
        std::shared_ptr<CC2F2ByteVector>>(m, "CC2F2ByteVector", D(CC2F2ByteVector))

        .def(py::init(&CC2F2ByteVector::make),
           py::arg("scale") = 1,
           py::arg("vecLength") = 1,
           py::arg("numVecItems") = 1,
           D(CC2F2ByteVector,make)
        )
        



        ;




}








