/*
 * Copyright 2022 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(costas4.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(07e40df1c47bcd5e7e7231e1aade786a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lfast/costas4.h>
// pydoc.h is automatically generated in the build directory
#include <costas4_pydoc.h>

void bind_costas4(py::module& m)
{

    using costas4    = ::gr::lfast::costas4;


    py::class_<costas4, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<costas4>>(m, "costas4", D(costas4))

        .def(py::init(&costas4::make),
           py::arg("loop_bw"),
           py::arg("order"),
           py::arg("genPDUs"),
           D(costas4,make)
        )
        




        
        .def("error",&costas4::error,       
            D(costas4,error)
        )

        ;




}








