/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MTFIRFilterCCC.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f8f9d735ffa6fb4e174073ee0642fc6b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lfast/MTFIRFilterCCC.h>
// pydoc.h is automatically generated in the build directory
#include <MTFIRFilterCCC_pydoc.h>

void bind_MTFIRFilterCCC(py::module& m)
{

    using MTFIRFilterCCC    = ::gr::lfast::MTFIRFilterCCC;


    py::class_<MTFIRFilterCCC, gr::sync_decimator,
        std::shared_ptr<MTFIRFilterCCC>>(m, "MTFIRFilterCCC", D(MTFIRFilterCCC))

        .def(py::init(&MTFIRFilterCCC::make),
           py::arg("decimation"),
           py::arg("taps"),
           py::arg("nthreads"),
           D(MTFIRFilterCCC,make)
        )
        




        
        .def("set_taps",&MTFIRFilterCCC::set_taps,       
            py::arg("taps"),
            D(MTFIRFilterCCC,set_taps)
        )


        
        .def("taps",&MTFIRFilterCCC::taps,       
            D(MTFIRFilterCCC,taps)
        )

        ;




}








