/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(MTFIRFilterFF.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(16914d02353fea6618bea70cc00b3e3d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lfast/MTFIRFilterFF.h>
// pydoc.h is automatically generated in the build directory
#include <MTFIRFilterFF_pydoc.h>

void bind_MTFIRFilterFF(py::module& m)
{

    using MTFIRFilterFF    = ::gr::lfast::MTFIRFilterFF;


    py::class_<MTFIRFilterFF, gr::sync_decimator,
        std::shared_ptr<MTFIRFilterFF>>(m, "MTFIRFilterFF", D(MTFIRFilterFF))

        .def(py::init(&MTFIRFilterFF::make),
           py::arg("decimation"),
           py::arg("taps"),
           py::arg("nthreads"),
           D(MTFIRFilterFF,make)
        )
        




        
        .def("set_taps",&MTFIRFilterFF::set_taps,       
            py::arg("taps"),
            D(MTFIRFilterFF,set_taps)
        )


        
        .def("taps",&MTFIRFilterFF::taps,       
            D(MTFIRFilterFF,taps)
        )

        ;




}








