/*
 * Copyright 2020 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(nlog10volk.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d68e42d357ebebbf602d82ecc0098608)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lfast/nlog10volk.h>
// pydoc.h is automatically generated in the build directory
#include <nlog10volk_pydoc.h>

void bind_nlog10volk(py::module& m)
{

    using nlog10volk    = ::gr::lfast::nlog10volk;


    py::class_<nlog10volk, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<nlog10volk>>(m, "nlog10volk", D(nlog10volk))

        .def(py::init(&nlog10volk::make),
           py::arg("n"),
           py::arg("vlen"),
           py::arg("k"),
           D(nlog10volk,make)
        )
        



        ;




}








